# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/waffle/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),waffle)

$(call add-radio-file-sha1-checked,radio/abl.img,fcabd28b430219471fbacb59399601689fa34950)
$(call add-radio-file-sha1-checked,radio/aop.img,64d08ca1d185d947d491b92fb4c9f8a9cd29f621)
$(call add-radio-file-sha1-checked,radio/aop_config.img,60b02da52a36ae170a3401403ce5ec8f0efeed8f)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,703b54e14f2cf66bf7a09575c746d2cfc4ec28ee)
$(call add-radio-file-sha1-checked,radio/cpucp.img,57856bde434ad991a523f2e706b770222f11a48f)
$(call add-radio-file-sha1-checked,radio/cpucp_dtb.img,d5153d4defb9d2acf523b3a518947119046f2c0f)
$(call add-radio-file-sha1-checked,radio/devcfg.img,996125ab15ce67848783236b2ed428ad4cdaad9d)
$(call add-radio-file-sha1-checked,radio/dsp.img,72075bb397712d2b7753e2a8654cf8e5c2313602)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,349c064ba9493d559cd94a4a2a96d4bf141147d7)
$(call add-radio-file-sha1-checked,radio/hyp.img,b1ca2b321d6fe3e02d87efe07e8500a6c2c9613c)
$(call add-radio-file-sha1-checked,radio/imagefv.img,7f687fa8bde8f15fd412137bf14760e6de6fc62e)
$(call add-radio-file-sha1-checked,radio/keymaster.img,055c7f20bbba3fec811f4ea69750449450871910)
$(call add-radio-file-sha1-checked,radio/modem.img,c1c3ab2a9b81869116ee81bdfc719fd5b7a958cf)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,2a0a3bc41fa77874e80515aaee0a151fd7ea2756)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,77c732e847aac4437909aa412a67b84646549ba5)
$(call add-radio-file-sha1-checked,radio/qupfw.img,095b574a125c369a8551842fda3410b08b4e7ad2)
$(call add-radio-file-sha1-checked,radio/shrm.img,056606ebac608f2bfe5997957ddbb8026fffb3fb)
$(call add-radio-file-sha1-checked,radio/splash.img,02a16b8f3e8f9f0214964ad40feadf06690fc526)
$(call add-radio-file-sha1-checked,radio/tz.img,cb83b725f64b29c09debfb37dae47063b7a8f3fa)
$(call add-radio-file-sha1-checked,radio/uefi.img,a84c3313866a09045911d4e3e94eea4921f6b29f)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,9b3703a59985f690f515b2efaf8231d3bfed40c9)
$(call add-radio-file-sha1-checked,radio/xbl.img,330969cf64e7941feed86e92e4d95ecf150addc1)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,21c8ceff3e16f22c1f9e52e88e32c3fe03c2e29f)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,9532ac95f6acf4a500ec743e1912b18ff396531d)

endif
