# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/waffle/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),waffle)

$(call add-radio-file-sha1-checked,radio/abl.img,b48e54da3a245a652918c1dfca078fa143e42fdc)
$(call add-radio-file-sha1-checked,radio/aop.img,d274af17af8d4ae771d2093797b045466665acdd)
$(call add-radio-file-sha1-checked,radio/aop_config.img,c27b955efd6d84c83193768905a043ef0a7c5ba7)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,adccdb443e620b082060e1d33819bc69699dede0)
$(call add-radio-file-sha1-checked,radio/cpucp.img,4e565b273cfb73d3a553690a4ee08c423ed1890d)
$(call add-radio-file-sha1-checked,radio/cpucp_dtb.img,1cef91b9281dbd3fde546b9acd2f19224ec3b8b4)
$(call add-radio-file-sha1-checked,radio/devcfg.img,b69b1871e48dcd9dd8a8846cc671e18e97b24726)
$(call add-radio-file-sha1-checked,radio/dsp.img,72075bb397712d2b7753e2a8654cf8e5c2313602)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,0df90213264e190ddbbb20376c83ca75d7932060)
$(call add-radio-file-sha1-checked,radio/hyp.img,e20134446bb148d6e1751369ed59892a36a7ca19)
$(call add-radio-file-sha1-checked,radio/imagefv.img,ea3a208f0d5933a04347a57f857204a7b0292d83)
$(call add-radio-file-sha1-checked,radio/keymaster.img,35452195f4b1a2919025466441492905eda74443)
$(call add-radio-file-sha1-checked,radio/modem.img,2826a02f19f76b03f1c43cb212d790334d957965)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,2a0a3bc41fa77874e80515aaee0a151fd7ea2756)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,477d3dff0ae1f9f73f3768f0ca674d77ab1d1e98)
$(call add-radio-file-sha1-checked,radio/qupfw.img,b145d9cf0f4aefb612c15672347bece6a767494e)
$(call add-radio-file-sha1-checked,radio/shrm.img,975bc6a8670777c41dd1c1ced309db17daa9e466)
$(call add-radio-file-sha1-checked,radio/splash.img,02a16b8f3e8f9f0214964ad40feadf06690fc526)
$(call add-radio-file-sha1-checked,radio/tz.img,5e2353376b6386b95bb5c0d66774485ae1dd648a)
$(call add-radio-file-sha1-checked,radio/uefi.img,ee3de642a4c8788417f57f7a31ce6da8ee080cce)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,c8b6db10b56becd1e20e003838972274acec5aa1)
$(call add-radio-file-sha1-checked,radio/xbl.img,691d590a93f21f53248c48570dc372baeca9f4a6)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,8301bbcd020809082ee8dd4378f061f619cf803f)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,4d977719347c7cc0f323a5e25402c44123ba6614)

endif
