# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/waffle/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),waffle)

$(call add-radio-file-sha1-checked,radio/abl.img,88b1ac0c00e6e4eeebed65ba979d96ef74bf12bb)
$(call add-radio-file-sha1-checked,radio/aop.img,ba5460f6d3bf446ba8c3f5be0cc55df3d89a7513)
$(call add-radio-file-sha1-checked,radio/aop_config.img,442b88d9311d5400e149f62758d5858258581325)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,37147f2d6d43b788d4ae9216bbde2dba6410e94d)
$(call add-radio-file-sha1-checked,radio/cpucp.img,242da9cbea31e1da3e93f7af63cf406c599b4370)
$(call add-radio-file-sha1-checked,radio/cpucp_dtb.img,17ff7c619985482df3034e6f46fc901df88da257)
$(call add-radio-file-sha1-checked,radio/devcfg.img,81af6344c8701ecbb5af3985f462ef5aa1777023)
$(call add-radio-file-sha1-checked,radio/dsp.img,72075bb397712d2b7753e2a8654cf8e5c2313602)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,e99ec56c97c18a2415d5d9c75b41ddfa06e64b6a)
$(call add-radio-file-sha1-checked,radio/hyp.img,5071eba5000151eda0ae83441046210d509084d7)
$(call add-radio-file-sha1-checked,radio/imagefv.img,31241b6dcd834382b7609e391155e03d4c986495)
$(call add-radio-file-sha1-checked,radio/keymaster.img,c72ccb83f856736c5c7490f00ec9bf79028f2486)
$(call add-radio-file-sha1-checked,radio/modem.img,8d009a293405d9125dda581894248248ccb829d9)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,2a0a3bc41fa77874e80515aaee0a151fd7ea2756)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,5c27c614aa8a7a0d6597261a7ddbf0710f4be84b)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0f8d364dc67af49fe472135b273ea35d90066b13)
$(call add-radio-file-sha1-checked,radio/shrm.img,418ef5ae175ff171e0c69b7f069f9e022a067d73)
$(call add-radio-file-sha1-checked,radio/splash.img,02a16b8f3e8f9f0214964ad40feadf06690fc526)
$(call add-radio-file-sha1-checked,radio/tz.img,e423251e54f2a4be9c81c593ce7e7c966a185149)
$(call add-radio-file-sha1-checked,radio/uefi.img,01531a1712c82b6971a15843b8be6ec51f0a3fcd)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,195e228a6bd375116248e6c487654741380ce8c3)
$(call add-radio-file-sha1-checked,radio/xbl.img,455fe628cc5e092d9449b0a44ba1ef3ef2072082)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a844b7d4d5d607ee9b836039430c713bcdca8f33)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,b1561a26df91d7fb2b73cc13d6de0a38c9b94bfd)

endif
