# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/waffle/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    aop \
    aop_config \
    bluetooth \
    cpucp \
    cpucp_dtb \
    devcfg \
    dsp \
    engineering_cdt \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    modem \
    oplus_sec \
    oplusstanvbk \
    qupfw \
    shrm \
    splash \
    tz \
    uefi \
    uefisecapp \
    xbl \
    xbl_config \
    xbl_ramdump
